SELECT ?item WHERE {
            { ?item wdt:P496 "0000-0003-4818-1595" } UNION
            { ?item rdfs:label "Maureen Walsh" } UNION
            { ?item skos:altLabel "Maureen Walsh" .
                SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en"}
        } }