SELECT ?item WHERE {
            { ?item wdt:P496 "0000-0002-9076-8595" } UNION
            { ?item rdfs:label "Thavamanithevi Subramaniam" } UNION
            { ?item skos:altLabel "Thavamanithevi Subramaniam" .
                SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en"}
        } }